### ISSUE TITLE
Mastermind

### ISSUE THREAD

**Issue by Teo2002** [Teaching-projects/SOE-ProgAlap1-Beadando-Mastermind-Polgar#1]

**Comment by Teo2002** [comment]
Jó szerencsét!
Úgy érzem, hogy elkészültem a vizsgafeladatommal. Meg tudnád nézni? 
Előre is nagyon szépen köszönöm!

**Comment by hegyhati** [comment]
Msot csak egy percet tudtam ralesni, Amit latok, hogy esetleg lehetne pimpelni, hogy ami van teszt (szuper, hogy vannak), azokat amit lehet attenni abba a formaba, ahogy utolso oran neztuk.

**Comment by hegyhati** [comment]
A program mukodese alapvetoen ok, bar azt nem ertem, hogy miert nem lehet tobbszor ugyanaz a szin. Ha ezt a logika leegyszerusitese miatt csinaltad, ok, bar kar. 

De van meg mit pofozni azert. Az egyik elso dolog, hogy nincs `Readme.md`, ahol le lenne irva, mit csinaltal, ezt tessek potolni :-)

A masik altalanos megjegyzes, hogy ez a 12 elemu lista, ami all 3 logikai reszbol ez elegge csunyacska, tessek kulon listakat hasznalni a kulonbozo dolgokra, ha egyben akarod kezelni, akkor meg azokat beletenni egy map-be. 

Osszertam par dolgot, ami atolvasas kozben jott, ha barmi nem vilagos, kerdezz.

`mastermind.py`
- [x] legjobb tudomasom szerint a mastermindban a feladavanyban es a tippben is lehet egy szin tobbszor.
- [x] a `general` fuggveny nem csak general, hanem ki is menti egy pickle-be. Hogy miert, azt meg nem latom, mindenesetre ezt a leirasaban is valoszinuleg erdemes megemliteni.
- [x] a `check`-ben nem tul szep logikai folyam, hogyha jo helyen van, akkor eloszor beleir egy RH-t, aztan atirja OK-ra az utolsot. inkabb akkor legyen elagazas, es 1x irjunk bele. 
- [x] A masik furcsasag itt, hogy van egy lista, amiben szinek vannak, es ennek a vegere fuzzuk hozza a kodjainkat, nem egy uj listaba tesszuk.
- [x] ugyanez a fura hozzafuzes ott van a szinkodban is
- [x] Amugy a szinkod oknak lehetne egy elore definialt map es akkor `kodok.append(szinkod[bevitel[i])`
- [x] A nyomtatban a for ciklus elso tesztje a h-tol sehogy nem fugg. Ha jol ertem, ez azt teszteli le, hogy kitalaltuk-e. Ezt mindenkeppen kitennem egy kulon fuggvenybe. De ezek a beegetett 9-12 indexek tenyleg nem tul szepek 
- [x] aztan jon a print, aminel huch, ember legyen a talpan, aki atlatja itt mi van. Szoval az lenne a szep, ha lenne egy tipped, ami a 4 szinbol allo lista, meg lenne egy ertekeles vagy tudomisen listad, amiben ezek az ok meg egyebek vannak, a szinkod meg jon egy map-bol vagy valami. Ehelyett a 4 soros print helyett meg egy for ciklus.
- [x] ugy altalaban (pl tipp) baratkozz meg a format stringekkel :-) 
- [x] check fuggvenyre lehetnenek tesztek itt
- [x] na ezt pl magyarazd el nekem, mit csinal: ` statisztika = [lista for listaban in statisztika for lista in listaban]`
- [x] a  szinozonben a `bevitelt` eloszor a feladvanyra hasznalod, aztan a bekert tippre. Ez igy elegge confusing.
- [x] nem szep ugye az sem, hogy `nyomtat` tetszteli le azt, hogy nyertunk-e, vagy sem, de ez mar elojott

`modositas.py`
Na itt latom, hogy benne vannk mar a tesztek, nice. Viszont ket peldany ne legyen a kodbol, takaritsd ki,amelyik nem kell :-)

Ez azokra a tesztekre is igaz, amik nem tudnak docstringbe bekerulni. OTt se legyen benne ujra a kod, hanem importald azt a fuggvenyt a masik py-bol.

**Comment by hegyhati** [comment]
Megj.: Most kepzeld el, hogy azt kernem Toled, hogy asjunk hozza meg ket szint, es 5 tipp legyen. Gondolom "nem esne jol". Es ez egy jele annak, hogy rosszu lvan strukturalva a kod, ha ilyen pici egyszeru modositasok nagy fejfajast okoznak, es 50 helyen at kell irni a kodot. Akkor lesz jo (Es jo lesz ;-) ) amikor egy ilyen modositas miatt at kell irni egy szamot 4-rol 5-re, meg egy listaba bele kell tenni meg ket szint, es a kodon semmi mast nem kell modositani.

**Comment by hegyhati** [comment]
Szia! Latom, pipalgattal,meg modositgattal. Nezzem?

**Comment by Teo2002** [comment]
Jó szerencsét!
Tanácsaidat megfogadva elkészültem az új programmal. Meg tudnád nézni? 
Előre is nagyon szépen köszönöm!

**Comment by hegyhati** [comment]
Tyuha, hat ennek nem sok koze van az elozohoz. Lehet most egyszerubb volna errol szoban beszelni, Radirok Teams-en.

**Comment by Teo2002** [comment]
Jó szerencsét!
Elkészültem a módosításokkal. Meg tudnád nézni őket? 
Előre is nagyon szépen köszönöm!

**Comment by hegyhati** [comment]
No szia. Hat most megint csinaltal valami 3-adikat, es mivel tok uj fajlok, nem latom a valtozast :-D Azt latom, hogy a dokumentaciok teljesen eltuntek, a tesztelos dolgot nem teljesen ertem, de majd megnezem jobban. A fuggvenyeid azert tovabbra is szep nagyok maradtak. Az mar tok jo, hogy map-et hasznalsz, ennek orulok, de miert conf1-conf4 a kulcsod, miert nem valami beszedesebb? :-)

Sajnos nem emlekszem, mi volt az a par dolog, amit szoban megbeszeltunk, hogy mindenkepp csinalj meg. Az map-ezesre emlekszem, az pipa, a tobbi mi volt? azokra akkor ranezek, aztan ha rendben, akkor adok egy otost, csak a conf-okat csereld meg le valami ertelmes nevre.

**Comment by hegyhati** [comment]
Jah, meg a dokumentaciokat tedd vissza, es 1 azaz EGY, EGY kodod legyen, ne egy egyokerben, meg egy V2-ben, meg... nem tudom. Most 4 copy is van ugyanabbol :-D Csak a vegleges legyen. ha kell a regi, ott van ra a git, vissza lehet nezni :-) 
![image](https://user-images.githubusercontent.com/13832329/105919105-4f9aa480-6035-11eb-9426-f525f46a1494.png)

**Comment by Teo2002** [comment]
Jó szerencsét!
Az általad kért változtatásokat – dictionary használata, szebb neveket adtam a conf-oknak – megcsináltam. A függvényeket nem tudom jobban szétszedni, szerintem logikailag így tartoznak össze.  A régi megoldásaimat töröltem GitHub-ról, így csak a végleges módosítás maradt. Igyekeztem minden kért változtatást megcsinálni, amit tudtam és ahogyan tudtam. Így sikerült…. 
Kíváncsian várom a vizsgajegyemet.

**Comment by hegyhati** [comment]
No, a tisztazasnak orulok, de  a dokumentaciot miert nem pdoc-kal? szep az a readme is, csak a pdoc megint ilyen mumus? Ugy remlik, csinaltal mar olyat pedig korabban.

**Comment by Teo2002** [comment]
Jó szerencsét!
Pdoc-kal is dokumentáltam a vizsgafeladatomat.

**Comment by hegyhati** [comment]
Jo, a generalt doc-ot majd pushold fel, de ezt az issue-t egy jelessel lezarom, tobb teendo itt nincs :-)
